package ua.lviv.lgs.domain;

public enum FacultyName {

	PHYSIC, HISTORY, PEDAGOGY, PHILOSOPHY, MATH, TOURISM, NATURAL_SCIENCES, EDUCATION, HUMANITIES,
	INFORMATION_TECHNOLOGY, ECONOMIC, COMPUTER_SCIENCES;

}
